version: '3.9'
x-customer-integrations:
  logs:
  metrics:

x-omnistrate-load-balancer:
  https:
    - name: frontend
      description: L7 Load Balancer for Web
      paths:
        - associatedResourceKey: web
          path: /
          backendPort: 80

services:
  web:
    image: nginxdemos/hello:0.4
    ports:
      - '80:80'
    environment:
      - SECURITY_CONTEXT_USER_ID=2000
      - SECURITY_CONTEXT_GROUP_ID=1000
